german_stopwords = {'nichts', 'hin', 'einigem', 'auf', 'selbst', 'sie', 'soll', 'weiter', 'alle', 'einen', 'einer',
                    'meinen', 'diesem', 'seinem', 'keiner', 'anderes', 'den', 'nicht', 'doch', 'meines', 'etwas',
                    'durch', 'sind', 'könnte', 'solchem', 'welches', 'keine', 'denselben', 'zwischen', 'einem', 'meine',
                    'einiges', 'ich', 'welche', 'sonst', 'eine', 'gewesen', 'desselben', 'mit', 'wieder', 'euch',
                    'würde', 'deiner', 'euren', 'das', 'jede', 'oder', 'da', 'dem', 'diese', 'hinter', 'meiner', 'so',
                    'am', 'gegen', 'andere', 'dass', 'anderr', 'bist', 'solche', 'viel', 'werden', 'würden', 'jeder',
                    'mich', 'kann', 'musste', 'dieselben', 'alles', 'als', 'andern', 'damit', 'des', 'dort', 'jedes',
                    'mancher', 'aber', 'jenen', 'ihre', 'ohne', 'dich', 'weg', 'ander', 'seines', 'unter', 'dazu',
                    'deinem', 'machen', 'welchen', 'zu', 'im', 'ihren', 'hier', 'sondern', 'war', 'für', 'nun', 'um',
                    'jener', 'unseres', 'waren', 'manche', 'mein', 'zur', 'anderen', 'meinem', 'aller', 'eure', 'derer',
                    'vor', 'uns', 'manchen', 'seinen', 'deines', 'hat', 'anders', 'und', 'in', 'wir', 'jeden',
                    'solcher', 'diesen', 'dasselbe', 'derselben', 'einmal', 'ihres', 'sein', 'von', 'anderer', 'jenem',
                    'dieser', 'der', 'während', 'ihrer', 'ob', 'jedem', 'an', 'also', 'wollen', 'sehr', 'jetzt',
                    'dieselbe', 'hab', 'ist', 'vom', 'einigen', 'welchem', 'indem', 'bin', 'deinen', 'warst', 'einige',
                    'unser', 'ihr', 'habe', 'er', 'demselben', 'dieses', 'welcher', 'jene', 'dessen', 'anderem', 'ein',
                    'wirst', 'euer', 'manches', 'einig', 'daß', 'sich', 'haben', 'man', 'ins', 'keinen', 'muss', 'nur',
                    'keines', 'werde', 'eures', 'eurem', 'sollte', 'seiner', 'eurer', 'hatte', 'jenes', 'ihnen',
                    'allen', 'ihn', 'hatten', 'anderm', 'unserem', 'seine', 'einiger', 'über', 'du', 'ihrem', 'aus',
                    'dies', 'dann', 'kein', 'unseren', 'will', 'wird', 'dein', 'zum', 'mir', 'ihm', 'wie', 'allem',
                    'derselbe', 'was', 'nach', 'auch', 'unsere', 'solchen', 'dir', 'bis', 'weil', 'eines', 'wenn',
                    'wollte', 'solches', 'bei', 'keinem', 'manchem', 'deine', 'wo', 'denn', 'noch', 'können', 'die',
                    'es', 'zwar', 'app', '...', 'b.', 'bzw.', 'e', 's', 't', 'z.b.', '..', 'a', 'u.a.', '\n', '\r'}

english_stopwords = {'i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll",
                     "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's",
                     'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs',
                     'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am',
                     'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does',
                     'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while',
                     'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during',
                     'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over',
                     'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all',
                     'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only',
                     'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't",
                     'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't",
                     'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't",
                     'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn',
                     "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won',
                     "won't", 'wouldn', "wouldn't", "\n", "\r"}
